name: Build and test project

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    
    env:
      Solution_Name: BaseRPG/BaseRPG.sln
      Test_Project_Path: BaseRPG/BaseRPGTests/BaseRPGTests.csproj
      Project_Path: BaseRPG/BaseRPG/BaseRPG.csproj

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Install packages
        run: dotnet restore ${{ env.Solution_Name }}
      - name: Build
        run: dotnet build ${{ env.Project_Path }}
      - name: Test
        run: dotnet test ${{ env.Test_Project_Path }}
        

